// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: h2blb-registered-target
// RUN: %clang_cc1 -O1 -triple h2blb -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: define dso_local i32 @widening_multiply_by_3(
// CHECK-SAME: i16 noundef signext [[A:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 asm "wsmul $0, $1, #3", "=r,r"(i16 [[A]]) #[[ATTR1:[0-9]+]], !srcloc [[META2:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int widening_multiply_by_3(short a) {
  int res;
  asm ("wsmul %0, %1, #3" : "=r" (res) : "r" (a));
  return res;
}
//.
// CHECK: [[META2]] = !{i64 616}
//.
