# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple h2blb -run-pass machine-scheduler  -o - %s | FileCheck %s -check-prefixes=DEFAULT
# RUN: llc -mtriple h2blb -run-pass machine-scheduler  -o - %s -mcpu generic | FileCheck %s -check-prefixes=GENERIC

# The read advance of the WSMUL comsumes one cycle of the latency of the LDR16.
# Therefore only one instruction needs to be scheduling between these
# two instructions.
---
name: sched
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1, $r2, $r3

    ; DEFAULT-LABEL: name: sched
    ; DEFAULT: liveins: $r0, $r1, $r2, $r3
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; DEFAULT-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; DEFAULT-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; DEFAULT-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; DEFAULT-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; DEFAULT-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; DEFAULT-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; DEFAULT-NEXT: [[WIDENING_SMUL:%[0-9]+]]:gpr32 = WIDENING_SMUL [[COPY]], [[LDR16_]]
    ; DEFAULT-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_SMUL]].sub_low16
    ; DEFAULT-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; DEFAULT-NEXT: RETURN implicit $r0, implicit $r1
    ;
    ; GENERIC-LABEL: name: sched
    ; GENERIC: liveins: $r0, $r1, $r2, $r3
    ; GENERIC-NEXT: {{  $}}
    ; GENERIC-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; GENERIC-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; GENERIC-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; GENERIC-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; GENERIC-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; GENERIC-NEXT: [[WIDENING_SMUL:%[0-9]+]]:gpr32 = WIDENING_SMUL [[COPY]], [[LDR16_]]
    ; GENERIC-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; GENERIC-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; GENERIC-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_SMUL]].sub_low16
    ; GENERIC-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; GENERIC-NEXT: RETURN implicit $r0, implicit $r1
    %0:gpr16 = COPY $r1
    %1:gpr16 = COPY $r2
    %2:gpr16 = COPY $r3
    %3:gpr16 = LDR16 %2, 0
    %4:gpr32 = WIDENING_SMUL %0, %3
    %5:gpr16 = ADDi16rr %0, %1
    %6:gpr16 = ADDi16rr %5, %5
    %7:gpr16 = ADDi16rr %6, %6
    %8:gpr16 = ADDi16rr %7, %4.sub_low16
    $r1 = COPY %8
    RETURN implicit $r0, implicit $r1
...
# WUMUL doesn't have read advance so the full two stall must be observed.
# (Or they must be filled with two instructions.)
---
name: sched_umul
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1, $r2, $r3

    ; DEFAULT-LABEL: name: sched_umul
    ; DEFAULT: liveins: $r0, $r1, $r2, $r3
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; DEFAULT-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; DEFAULT-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; DEFAULT-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; DEFAULT-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; DEFAULT-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; DEFAULT-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; DEFAULT-NEXT: [[WIDENING_UMUL:%[0-9]+]]:gpr32 = WIDENING_UMUL [[COPY]], [[LDR16_]]
    ; DEFAULT-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_UMUL]].sub_low16
    ; DEFAULT-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; DEFAULT-NEXT: RETURN implicit $r0, implicit $r1
    ;
    ; GENERIC-LABEL: name: sched_umul
    ; GENERIC: liveins: $r0, $r1, $r2, $r3
    ; GENERIC-NEXT: {{  $}}
    ; GENERIC-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; GENERIC-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; GENERIC-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; GENERIC-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; GENERIC-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; GENERIC-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; GENERIC-NEXT: [[WIDENING_UMUL:%[0-9]+]]:gpr32 = WIDENING_UMUL [[COPY]], [[LDR16_]]
    ; GENERIC-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; GENERIC-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_UMUL]].sub_low16
    ; GENERIC-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; GENERIC-NEXT: RETURN implicit $r0, implicit $r1
    %0:gpr16 = COPY $r1
    %1:gpr16 = COPY $r2
    %2:gpr16 = COPY $r3
    %3:gpr16 = LDR16 %2, 0
    %4:gpr32 = WIDENING_UMUL %0, %3
    %5:gpr16 = ADDi16rr %0, %1
    %6:gpr16 = ADDi16rr %5, %5
    %7:gpr16 = ADDi16rr %6, %6
    %8:gpr16 = ADDi16rr %7, %4.sub_low16
    $r1 = COPY %8
    RETURN implicit $r0, implicit $r1
...
# Demonstrate how to use scheduling strategies to hide latency.
# In this example, with a default top-down scheduler, we would
# run out of candidates to hide the latency of the SMUL instruction.
---
name: strategy_for_wsmul
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $r0, $r1, $r2, $r3

    ; DEFAULT-LABEL: name: strategy_for_wsmul
    ; DEFAULT: liveins: $r0, $r1, $r2, $r3
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; DEFAULT-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; DEFAULT-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; DEFAULT-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; DEFAULT-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; DEFAULT-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; DEFAULT-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; DEFAULT-NEXT: [[WIDENING_SMUL:%[0-9]+]]:gpr32 = WIDENING_SMUL [[COPY]], [[LDR16_]]
    ; DEFAULT-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_SMUL]].sub_low16
    ; DEFAULT-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; DEFAULT-NEXT: RETURN implicit $r0, implicit $r1
    ;
    ; GENERIC-LABEL: name: strategy_for_wsmul
    ; GENERIC: liveins: $r0, $r1, $r2, $r3
    ; GENERIC-NEXT: {{  $}}
    ; GENERIC-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r1
    ; GENERIC-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r2
    ; GENERIC-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r3
    ; GENERIC-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY2]], 0
    ; GENERIC-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY]], [[COPY1]]
    ; GENERIC-NEXT: [[ADDi16rr1:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr]], [[ADDi16rr]]
    ; GENERIC-NEXT: [[ADDi16rr2:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr1]], [[ADDi16rr1]]
    ; GENERIC-NEXT: [[WIDENING_SMUL:%[0-9]+]]:gpr32 = WIDENING_SMUL [[COPY]], [[LDR16_]]
    ; GENERIC-NEXT: [[ADDi16rr3:%[0-9]+]]:gpr16 = ADDi16rr [[ADDi16rr2]], [[WIDENING_SMUL]].sub_low16
    ; GENERIC-NEXT: $r1 = COPY [[ADDi16rr3]]
    ; GENERIC-NEXT: RETURN implicit $r0, implicit $r1
    %0:gpr16 = COPY $r1
    %1:gpr16 = COPY $r2
    %2:gpr16 = COPY $r3
    %3:gpr16 = LDR16 %2, 0
    %5:gpr16 = ADDi16rr %0, %1
    %6:gpr16 = ADDi16rr %5, %5
    %7:gpr16 = ADDi16rr %6, %6
    %4:gpr32 = WIDENING_SMUL %0, %3
    %8:gpr16 = ADDi16rr %7, %4.sub_low16
    $r1 = COPY %8
    RETURN implicit $r0, implicit $r1
...
