; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb -o - %s -fast-isel=0 -verify-machineinstrs | FileCheck %s

define i16 @extractVecEltLow(<2 x i16> %a) {
; CHECK-LABEL: extractVecEltLow:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov16 r1, r2
; CHECK-NEXT:    ret
  %res = extractelement <2 x i16> %a, i16 0
  ret i16 %res
}

define i16 @extractVecEltHigh(<2 x i16> %a) {
; CHECK-LABEL: extractVecEltHigh:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov16 r1, r3
; CHECK-NEXT:    ret
  %res = extractelement <2 x i16> %a, i16 1
  ret i16 %res
}
