; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; Check the lowering with the selection pattern mul(sext,sext).
; RUN: llc -fast-isel=0 -h2blb-lower-mul-mode=0 -o - %s | FileCheck %s
; Check the lowering with custom legalization of mul.
; RUN: llc -fast-isel=0 -h2blb-lower-mul-mode=1 -o - %s | FileCheck %s
target triple="h2blb"

define i32 @widening_smul(i16 %a, i16 %b) {
; CHECK-LABEL: widening_smul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    wsmul d1, r1, r2
; CHECK-NEXT:    ret
  %sexta = sext i16 %a to i32
  %sextb = sext i16 %b to i32
  %res = mul i32 %sexta, %sextb
  ret i32 %res
}

define i32 @widening_umul(i16 %a, i16 %b) {
; CHECK-LABEL: widening_umul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    wumul d1, r1, r2
; CHECK-NEXT:    ret
  %zexta = zext i16 %a to i32
  %zextb = zext i16 %b to i32
  %res = mul i32 %zexta, %zextb
  ret i32 %res
}
