; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc %s -mtriple h2blb -o - -verify-machineinstrs -enable-misched=false | FileCheck %s

define void @scalarizeAndCallLib(ptr %src, ptr %dst) {
; CHECK-LABEL: scalarizeAndCallLib:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subsp sp, sp, 16
; CHECK-NEXT:    strsp32 d2, sp, 12 # 4-byte Folded Spill
; CHECK-NEXT:    strsp32 d3, sp, 8 # 4-byte Folded Spill
; CHECK-NEXT:    mov16 r4, r0
; CHECK-NEXT:    mov16 r5, r2
; CHECK-NEXT:    mov16 r6, r1
; CHECK-NEXT:    movfromsp r0, sp
; CHECK-NEXT:    ldr32 d1, r6, 4
; CHECK-NEXT:    str32 d1, r0, 0
; CHECK-NEXT:    call __addsf3
; CHECK-NEXT:    ldr32 d0, r6, 0
; CHECK-NEXT:    movfromsp r6, sp
; CHECK-NEXT:    str32 d0, r6, 0
; CHECK-NEXT:    str32 d1, r5, 4
; CHECK-NEXT:    mov32 d1, d0
; CHECK-NEXT:    call __addsf3
; CHECK-NEXT:    str32 d1, r5, 0
; CHECK-NEXT:    mov16 r0, r4
; CHECK-NEXT:    ldrsp32 d3, sp, 8 # 4-byte Folded Reload
; CHECK-NEXT:    ldrsp32 d2, sp, 12 # 4-byte Folded Reload
; CHECK-NEXT:    addsp sp, sp, 16
; CHECK-NEXT:    ret
  %val = load <2 x float>, ptr %src
  %res = fadd <2 x float> %val, %val
  store <2 x float> %res, ptr %dst
  ret void
}
