; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc %s -mtriple h2blb--darwin -o - | FileCheck %s

define i16 @andi16(i16 %a, i16 %b) {
; CHECK-LABEL: andi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = and i16 %a, %b
  ret i16 %res
}

define i16 @andi16Imm(i16 %a) {
; CHECK-LABEL: andi16Imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi16 r2, 6
; CHECK-NEXT:    and16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = and i16 %a, 6
  ret i16 %res
}

define i32 @andi32(i32 %a, i32 %b) {
; CHECK-LABEL: andi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subsp sp, sp, 4
; CHECK-NEXT:    strsp32 d2, sp, 0 # 4-byte Folded Spill
; CHECK-NEXT:    ldrsp32 d2, sp, 4
; CHECK-NEXT:    and32 d1, d1, d2
; CHECK-NEXT:    ldrsp32 d2, sp, 0 # 4-byte Folded Reload
; CHECK-NEXT:    addsp sp, sp, 4
; CHECK-NEXT:    ret
  %res = and i32 %a, %b
  ret i32 %res
}

define i32 @andi32Imm(i32 %a) {
; CHECK-LABEL: andi32Imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subsp sp, sp, 4
; CHECK-NEXT:    strsp32 d2, sp, 0 # 4-byte Folded Spill
; CHECK-NEXT:    ldi32 d2, 6
; CHECK-NEXT:    and32 d1, d1, d2
; CHECK-NEXT:    ldrsp32 d2, sp, 0 # 4-byte Folded Reload
; CHECK-NEXT:    addsp sp, sp, 4
; CHECK-NEXT:    ret
  %res = and i32 %a, 6
  ret i32 %res
}
