; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb -o - %s | FileCheck %s

define i16 @loadi16(ptr %arg) {
; CHECK-LABEL: loadi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldr16 r1, r1, 0
; CHECK-NEXT:    ret
  %res = load i16, ptr %arg
  ret i16 %res
}
