# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -global-isel -global-isel-abort=1 -start-before=instruction-select \
# RUN:     -stop-after=finalize-isel -verify-machineinstrs -o - -mtriple h2blb--darwin | FileCheck %s

# Check that G_PTR_ADD is eventually lowered to ADDi16rr despite using a
# pseudo operation during selection.
---
name: selectAdd
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: selectAdd
    ; CHECK: liveins: $r1, $r2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r2
    ; CHECK-NEXT: [[ADDi16rr:%[0-9]+]]:gpr16 = ADDi16rr [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $r1 = COPY [[ADDi16rr]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RETURN implicit $r1, implicit $r0
    %0:gprb(p0) = COPY $r1
    %1:gprb(s16) = COPY $r2
    %2:gprb(p0) = G_PTR_ADD %0, %1
    $r1 = COPY %2
    RET_PSEUDO implicit $r1
...
