# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -global-isel -global-isel-abort=1 -run-pass=instruction-select -o - -mtriple h2blb | FileCheck %s
---
name: selectStorei16
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: selectStorei16
    ; CHECK: liveins: $r1, $r2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r2
    ; CHECK-NEXT: STR16 [[COPY1]], [[COPY2]], 0 :: (store (s16))
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO
    %0:gprb(s16) = COPY $r1
    %1:gprb(p0) = COPY $r2
    G_STORE %0, %1 :: (store(s16))
    RET_PSEUDO
...
---
name: selectStorei32
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $d1

    ; CHECK-LABEL: name: selectStorei32
    ; CHECK: liveins: $r1, $d1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
    ; CHECK-NEXT: STR32 [[COPY2]], [[COPY1]], 0 :: (store (s32))
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO
    %0:gprb(p0) = COPY $r1
    %1:gprb(s32) = COPY $d1
    G_STORE %1, %0 :: (store(s32))
    RET_PSEUDO
...
---
name: selectStorev2i16
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $d1

    ; CHECK-LABEL: name: selectStorev2i16
    ; CHECK: liveins: $r1, $d1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr32 = COPY $d1
    ; CHECK-NEXT: STR32 [[COPY2]], [[COPY1]], 0 :: (store (<2 x s16>))
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO
    %0:gprb(p0) = COPY $r1
    %1:gprb(<2 x s16>) = COPY $d1
    G_STORE %1, %0 :: (store(<2 x s16>))
    RET_PSEUDO
...
