# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -global-isel -global-isel-abort=1 -run-pass=instruction-select -o - -mtriple h2blb--darwin | FileCheck %s
---
name: selectAdd
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: selectAdd
    ; CHECK: liveins: $r1, $r2, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY $r2
    ; CHECK-NEXT: [[PTR_ADD16rr:%[0-9]+]]:gpr16 = PTR_ADD16rr [[COPY1]], [[COPY2]]
    ; CHECK-NEXT: $r1 = COPY [[PTR_ADD16rr]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:gprb(p0) = COPY $r1
    %1:gprb(s16) = COPY $r2
    %2:gprb(p0) = G_PTR_ADD %0, %1
    $r1 = COPY %2
    RET_PSEUDO implicit $r1
...
