# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -global-isel -global-isel-abort=1 -run-pass=instruction-select -o - -mtriple h2blb--darwin | FileCheck %s
---
name: selectExtractVectorEltLow
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $d1

    ; CHECK-LABEL: name: selectExtractVectorEltLow
    ; CHECK: liveins: $d1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr32 = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY [[COPY1]].sub_low16
    ; CHECK-NEXT: $r1 = COPY [[COPY2]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:gprb(<2 x s16>) = COPY $d1
    %1:gprb(s16) = G_CONSTANT i16 0
    %2:gprb(s16) = G_EXTRACT_VECTOR_ELT %0, %1
    $r1 = COPY %2
    RET_PSEUDO implicit $r1
...
---
name: selectExtractVectorEltHigh
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $d1

    ; CHECK-LABEL: name: selectExtractVectorEltHigh
    ; CHECK: liveins: $d1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr32 = COPY $d1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gpr16 = COPY [[COPY1]].sub_high16
    ; CHECK-NEXT: $r1 = COPY [[COPY2]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:gprb(<2 x s16>) = COPY $d1
    %1:gprb(s16) = G_CONSTANT i16 1
    %2:gprb(s16) = G_EXTRACT_VECTOR_ELT %0, %1
    $r1 = COPY %2
    RET_PSEUDO implicit $r1
...
