# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -global-isel -global-isel-abort=1 -run-pass=instruction-select -o - -mtriple h2blb--darwin | FileCheck %s
---
name: selectLoad
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: selectLoad
    ; CHECK: liveins: $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY1]], 0 :: (load (s16))
    ; CHECK-NEXT: $r1 = COPY [[LDR16_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:gprb(p0) = COPY $r1
    %1:gprb(s16) = G_LOAD %0 :: (load(s16))
    $r1 = COPY %1
    RET_PSEUDO implicit $r1
...
---
name: selectLoadPlusImm
legalized: true
regBankSelected: true
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $r1

    ; CHECK-LABEL: name: selectLoadPlusImm
    ; CHECK: liveins: $r1, $r0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr16 = COPY $r0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
    ; CHECK-NEXT: [[LDR16_:%[0-9]+]]:gpr16 = LDR16 [[COPY1]], 7 :: (load (s16))
    ; CHECK-NEXT: $r1 = COPY [[LDR16_]]
    ; CHECK-NEXT: $r0 = COPY [[COPY]]
    ; CHECK-NEXT: RET_PSEUDO implicit $r1
    %0:gprb(p0) = COPY $r1
    %1:gprb(s16) = G_CONSTANT i16 7
    %2:gprb(p0) = G_PTR_ADD %0, %1
    %3:gprb(s16) = G_LOAD %2 :: (load(s16))
    $r1 = COPY %3
    RET_PSEUDO implicit $r1
...
