# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -run-pass=h2blb-mandatory-prelegalizer-combiner %s -o - -mtriple=h2blb -verify-machineinstrs | FileCheck %s

---
name: insertElt2BuildVector
tracksRegLiveness: true
body:             |
  bb.1:
    liveins: $r1, $r2

    ; CHECK-LABEL: name: insertElt2BuildVector
    ; CHECK: liveins: $r1, $r2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:_(<2 x s16>) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $r1
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s16) = COPY $r2
    ; CHECK-NEXT: %cst0:_(s16) = G_CONSTANT i16 0
    ; CHECK-NEXT: %cst1:_(s16) = G_CONSTANT i16 1
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:_(s16) = G_IMPLICIT_DEF
    ; CHECK-NEXT: [[BUILD_VECTOR:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[COPY]](s16), [[DEF1]](s16)
    ; CHECK-NEXT: [[BUILD_VECTOR1:%[0-9]+]]:_(<2 x s16>) = G_BUILD_VECTOR [[COPY]](s16), [[COPY1]](s16)
    ; CHECK-NEXT: $d1 = COPY [[BUILD_VECTOR1]](<2 x s16>)
    ; CHECK-NEXT: RET_PSEUDO implicit $d1
    %0:_(<2 x s16>) = G_IMPLICIT_DEF
    %1:_(s16) = COPY $r1
    %2:_(s16) = COPY $r2
    %cst0:_(s16) = G_CONSTANT i16 0
    %cst1:_(s16) = G_CONSTANT i16 1
    %3:_(<2 x s16>) = G_INSERT_VECTOR_ELT %0, %1, %cst0
    %4:_(<2 x s16>) = G_INSERT_VECTOR_ELT %3, %2, %cst1
    $d1 = COPY %4
    RET_PSEUDO implicit $d1

...
