; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc  -o - %s -global-isel -global-isel-abort=1 | FileCheck %s
target triple="h2blb--"

define i16 @ldi16() {
; CHECK-LABEL: ldi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi16 r1, 13
; CHECK-NEXT:    ret
  ret i16 13
}

define i32 @ldi32() {
; CHECK-LABEL: ldi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi32 d1, 123
; CHECK-NEXT:    ret
  ret i32 123
}
