; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

define i16 @trunc16(i32 %a) {
; CHECK-LABEL: trunc16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov16 r1, r2
; CHECK-NEXT:    ret
  %res = trunc i32 %a to i16
  ret i16 %res
}
