; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

define i16 @addi16(i16 %a, i16 %b) {
; CHECK-LABEL: addi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = add i16 %a, %b
  ret i16 %res
}

define i16 @addi16Imm(i16 %a) {
; CHECK-LABEL: addi16Imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi16 r2, 6
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = add i16 %a, 6
  ret i16 %res
}

define ptr @ptrAdd(ptr %base, i16 %offset) {
; CHECK-LABEL: ptrAdd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %base, i16 %offset
  ret ptr %addr
}
