; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s
; Regular function calls must use symbols be defined or declared in the same
; module.
; However, for intrinsics, the middle-end is able to add the declarations
; on the fly.
; Therefore, this test passes if the h2blb intrinsics are properly hooked up.

target triple="h2blb"

define i32 @widening_smul(i16 %a, i16 %b) {
; CHECK-LABEL: widening_smul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    wsmul d1, r1, r2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.h2blb.widening.smul(i16 %a, i16 %b)
  ret i32 %res
}

define i32 @widening_umul(i16 %a, i16 %b) {
; CHECK-LABEL: widening_umul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    wumul d1, r1, r2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.h2blb.widening.umul(i16 %a, i16 %b)
  ret i32 %res
}
