; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb--darwin -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs -stop-after=finalize-isel | FileCheck %s
; These tests are ISel-only until we implement the lowering of the stack.
; Indeed when we create allocas, we need to lower the related FrameIndex and
; create some space on the stack.

declare void @other(ptr)

define void @frameIndex() {
  ; CHECK-LABEL: name: frameIndex
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr16 = COPY $r0
  ; CHECK-NEXT:   [[MOVFROMSP:%[0-9]+]]:gpr16 = MOVFROMSP %stack.0.value
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r1 = COPY [[MOVFROMSP]]
  ; CHECK-NEXT:   CALL @other, csr, implicit-def $r0, implicit $sp, implicit $r1
  ; CHECK-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   $r0 = COPY [[COPY]]
  ; CHECK-NEXT:   RETURN implicit $r0
  %value = alloca i32
  call void @other(ptr %value)
  ret void
}
