; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb--darwin -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs -stop-after=finalize-isel | FileCheck %s
; These tests are ISel-only until we implement the lowering of the stack.
; Indeed when we create allocas, we need to lower the related FrameIndex and
; create some space on the stack.

; We make the load volatile because otherwise SDISel optimize it away since it
; knows we are loading the value that we just stored.
define i16 @alloca16(i16 %val) {
  ; CHECK-LABEL: name: alloca16
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $r1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr16 = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr16 = COPY $r1
  ; CHECK-NEXT:   STRSP16 [[COPY1]], %stack.0.ptr, 0 :: (store (s16) into %ir.ptr)
  ; CHECK-NEXT:   [[LDRSP16_:%[0-9]+]]:gpr16 = LDRSP16 %stack.0.ptr, 0 :: (volatile dereferenceable load (s16) from %ir.ptr)
  ; CHECK-NEXT:   $r1 = COPY [[LDRSP16_]]
  ; CHECK-NEXT:   $r0 = COPY [[COPY]]
  ; CHECK-NEXT:   RETURN implicit $r1, implicit $r0
  %ptr = alloca i16
  store i16 %val, ptr %ptr
  %res = load volatile i16, ptr %ptr
  ret i16 %res
}

define i32 @alloca32(i32 %val) {
  ; CHECK-LABEL: name: alloca32
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $d1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr16 = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $d1
  ; CHECK-NEXT:   STRSP32 [[COPY1]], %stack.0.ptr, 0 :: (store (s32) into %ir.ptr)
  ; CHECK-NEXT:   [[LDRSP32_:%[0-9]+]]:gpr32 = LDRSP32 %stack.0.ptr, 0 :: (volatile dereferenceable load (s32) from %ir.ptr)
  ; CHECK-NEXT:   $d1 = COPY [[LDRSP32_]]
  ; CHECK-NEXT:   $r0 = COPY [[COPY]]
  ; CHECK-NEXT:   RETURN implicit $d1, implicit $r0
  %ptr = alloca i32
  store i32 %val, ptr %ptr
  %res = load volatile i32, ptr %ptr
  ret i32 %res
}

define i16 @alloca32SExtLoad(i32 %val) {
  ; CHECK-LABEL: name: alloca32SExtLoad
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $d1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr16 = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $d1
  ; CHECK-NEXT:   STRSP32 [[COPY1]], %stack.0.ptr, 0 :: (store (s32) into %ir.ptr)
  ; CHECK-NEXT:   [[LDRSEXTSP8_:%[0-9]+]]:gpr16 = LDRSEXTSP8 %stack.0.ptr, 0 :: (volatile dereferenceable load (s8) from %ir.ptr)
  ; CHECK-NEXT:   $r1 = COPY [[LDRSEXTSP8_]]
  ; CHECK-NEXT:   $r0 = COPY [[COPY]]
  ; CHECK-NEXT:   RETURN implicit $r1, implicit $r0
  %ptr = alloca i32
  store i32 %val, ptr %ptr
  %ld = load volatile i8, ptr %ptr
  %res = sext i8 %ld to i16
  ret i16 %res
}

define i16 @alloca32ZExtLoad(i32 %val) {
  ; CHECK-LABEL: name: alloca32ZExtLoad
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $d1, $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr16 = COPY $r0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr32 = COPY $d1
  ; CHECK-NEXT:   STRSP32 [[COPY1]], %stack.0.ptr, 0 :: (store (s32) into %ir.ptr)
  ; CHECK-NEXT:   [[LDRZEXTSP8_:%[0-9]+]]:gpr16 = LDRZEXTSP8 %stack.0.ptr, 0 :: (volatile dereferenceable load (s8) from %ir.ptr)
  ; CHECK-NEXT:   $r1 = COPY [[LDRZEXTSP8_]]
  ; CHECK-NEXT:   $r0 = COPY [[COPY]]
  ; CHECK-NEXT:   RETURN implicit $r1, implicit $r0
  %ptr = alloca i32
  store i32 %val, ptr %ptr
  %ld = load volatile i8, ptr %ptr
  %res = zext i8 %ld to i16
  ret i16 %res
}
