; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple h2blb--darwin -o - %s -global-isel=1 -global-isel-abort=1 -verify-machineinstrs | FileCheck %s

define i16 @addi16(i16 %a, i16 %b) {
; CHECK-LABEL: addi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = add i16 %a, %b
  ret i16 %res
}

define i16 @addi16Imm(i16 %a) {
; CHECK-LABEL: addi16Imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ldi16 r2, 6
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %res = add i16 %a, 6
  ret i16 %res
}

define ptr @ptrAdd(ptr %base, i16 %offset) {
; CHECK-LABEL: ptrAdd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi16 r1, r1, r2
; CHECK-NEXT:    ret
  %addr = getelementptr i8, ptr %base, i16 %offset
  ret ptr %addr
}

define <2 x i16> @addv2i16(<2 x i16> %a) {
; CHECK-LABEL: addv2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subsp sp, sp, 4
; CHECK-NEXT:    strsp32 d2, sp, 0 # 4-byte Folded Spill
; CHECK-NEXT:    addi16 r4, r2, r2
; CHECK-NEXT:    addi16 r5, r3, r3
; CHECK-NEXT:    mov32 d1, d2
; CHECK-NEXT:    ldrsp32 d2, sp, 0 # 4-byte Folded Reload
; CHECK-NEXT:    addsp sp, sp, 4
; CHECK-NEXT:    ret
  %res = add <2 x i16> %a, %a
  ret <2 x i16> %res
}
